#include <iostream>
#include <iomanip>
#include <cmath>
#include <math.h>
int main() {
	using namespace std;
	double x1, x2, x3, y1, y2, y3, l1, l2, l3, h1, h2, h3, m1, m2, m3, b1, b2, b3, R, r, LR, Lr, SR, Sr, P, S, p, g1, g2, g3, r1, r2, r3, z1, z2, z3, pi, S1, S2;
	cin >> x1;
	cin >> y1;
	cin >> x2;
	cin>> y2;
	cin>> x3;
	cin>> y3;
	pi = acos(-1);
	l1 = sqrt(pow((x2 - x1), 2) + pow((y2 - y1), 2));
	l2 = sqrt(pow((x3 - x2), 2) + pow((y3 - y2), 2));
	l3 = sqrt(pow((x3 - x1), 2) + pow((y3 - y1), 2));
	p = (l1 + l2 + l3) / 2;
	S = sqrt(p * (p - l1) * (p - l2) * (p - l3));
	h1 = 2 * S / l1;
	h2 = 2 * S / l2;
	h3 = 2 * S / l3;
	m1 = sqrt(2 * pow(l3, 2) + 2 * pow(l2, 2) - pow(l1, 2)) / 2;
	m2 = sqrt(2 * pow(l1, 2) + 2 * pow(l3, 2) - pow(l2, 2)) / 2;
	m3 = sqrt(2 * pow(l1, 2) + 2 * pow(l2, 2) - pow(l3, 2)) / 2;
	b1 = 2 * sqrt(l3 * l2 * p * (p - l1)) / (l3 + l2);
	b2 = 2 * sqrt(l1 * l3 * p * (p - l2)) / (l1 + l3);
	b3 = 2 * sqrt(l1 * l2 * p * (p - l3)) / (l1 + l2);
	z1 = (pow(l3, 2) + pow(l2, 2) - pow(l1, 2)) / (2 * l2 * l3);
	z2 = (pow(l1, 2) + pow(l3, 2) - pow(l2, 2)) / (2 * l1 * l3);
	z3 = (pow(l1, 2) + pow(l2, 2) - pow(l3, 2)) / (2 * l2 * l3);
	r1 = acos(z1);
	r2 = acos(z2);
	r3 = acos(z3);
	g1 = r1 * 180 / pi;
	g2 = r2 * 180 / pi;
	g3 = r3 * 180 / pi;
	r = S / p;
	R = l1 * l2 * l3 / (4 * S);
	LR = 2 * pi * R;
	Lr = 2 * pi * r;
	SR = pi * pow(R, 2);
	Sr = pi * pow(r, 2);
	P = p * 2;
	S1 = l1 * h1 * 0.5;
	S2 = l1 * l2 * sin(r3) * 0.5;
	std::cout << setprecision(5) << l1;
	std::cout << "\n";
	std::cout << setprecision(5) << l2;
	std::cout << "\n";
	std::cout << setprecision(5) << l3;
	std::cout << "\n";
	std::cout << setprecision(5) << h1;
	std::cout << "\n";
	std::cout << setprecision(5) << h2;
	std::cout << "\n";
	std::cout << setprecision(5) << h3; std::cout  << "\n";
	std::cout << setprecision(5) << m1; std::cout << "\n";
	std::cout << setprecision(5) << m2; std::cout << "\n";
	std::cout << setprecision(5) << m3; std::cout << "\n";
	std::cout << setprecision(5) << b1; std::cout << "\n";
	std::cout << setprecision(5) << b2; std::cout << "\n";
	std::cout << setprecision(5) << b3; std::cout << "\n";
	std::cout << setprecision(5) << r2;
	std::cout << setprecision(5) << " " << g2; std::cout << "\n";
	std::cout << setprecision(5) << r3;
	std::cout << setprecision(5) << " " << g3; std::cout << "\n";
	std::cout << setprecision(5) << r1;
	std::cout << setprecision(5) << " " << g1; std::cout << "\n";
	std::cout << setprecision(5) << R; std::cout << "\n";
	std::cout << setprecision(5) << r; std::cout << "\n";
	std::cout << setprecision(5) << Lr; std::cout << "\n";
	std::cout << setprecision(5) << Sr; std::cout << "\n";
	std::cout << setprecision(5) << LR; std::cout <<  "\n";
	std::cout << setprecision(5) << SR; std::cout << "\n";
	std::cout << setprecision(5) << "Square of triangle = " << S << " or " << S1 << " or " << S2;
	std::cout << "\n";
	std::cout << setprecision(5) << P;
	return 0;
}